### ISSUE TITLE
bug:不能打开微博的视频

### ISSUE THREAD

**Issue by JWleo** [Ha2ryZhang/hotsearch#1]
OS:
centos 7

vscode:
Version: 1.49.1
Commit: 58bb7b2331731bf72587010e943852e13e6fd3cf
Date: 2020-09-16T23:23:33.049Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 3.10.0-957.el7.x86_64

热搜内的视频不能打开播放，效果如下：
![捕获](https://user-images.githubusercontent.com/32316654/163138950-f0acc01e-4c0d-48bb-9a40-d88d8c345e73.PNG)

**Comment by Ha2ryZhang** [comment]
@JWleo vscode 的webview 好像没有包含ffmpeg 不能播放视频
